global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "vector-search-engine-coordinators"
    static_configs:
      - targets: ["coordinator-active:8000", "coordinator-standby:8000"]
