# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vector_engine.app.proto import engine_pb2 as vector__engine_dot_app_dot_proto_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vector_engine/app/proto/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchWorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertVector = channel.unary_unary(
                '/engine.SearchWorker/InsertVector',
                request_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.InsertRequest.SerializeToString,
                response_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.SearchVectors = channel.unary_unary(
                '/engine.SearchWorker/SearchVectors',
                request_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/engine.SearchWorker/HealthCheck',
                request_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ClearIndex = channel.unary_unary(
                '/engine.SearchWorker/ClearIndex',
                request_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.ClearRequest.SerializeToString,
                response_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.ClearResponse.FromString,
                _registered_method=True)


class SearchWorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def InsertVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertVector': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertVector,
                    request_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.InsertRequest.FromString,
                    response_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.InsertResponse.SerializeToString,
            ),
            'SearchVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVectors,
                    request_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.SearchRequest.FromString,
                    response_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.SearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.HealthRequest.FromString,
                    response_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.HealthResponse.SerializeToString,
            ),
            'ClearIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearIndex,
                    request_deserializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.ClearRequest.FromString,
                    response_serializer=vector__engine_dot_app_dot_proto_dot_engine__pb2.ClearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.SearchWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.SearchWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchWorker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.SearchWorker/InsertVector',
            vector__engine_dot_app_dot_proto_dot_engine__pb2.InsertRequest.SerializeToString,
            vector__engine_dot_app_dot_proto_dot_engine__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.SearchWorker/SearchVectors',
            vector__engine_dot_app_dot_proto_dot_engine__pb2.SearchRequest.SerializeToString,
            vector__engine_dot_app_dot_proto_dot_engine__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.SearchWorker/HealthCheck',
            vector__engine_dot_app_dot_proto_dot_engine__pb2.HealthRequest.SerializeToString,
            vector__engine_dot_app_dot_proto_dot_engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.SearchWorker/ClearIndex',
            vector__engine_dot_app_dot_proto_dot_engine__pb2.ClearRequest.SerializeToString,
            vector__engine_dot_app_dot_proto_dot_engine__pb2.ClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
