# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_engine/app/proto/engine.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'vector_engine/app/proto/engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$vector_engine/app/proto/engine.proto\x12\x06\x65ngine\"B\n\rInsertRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\"2\n\x0eInsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\".\n\rSearchRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\r\n\x05top_k\x18\x02 \x01(\x05\"@\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\"7\n\x0eSearchResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.engine.SearchResult\"\x0f\n\rHealthRequest\".\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\"\x0e\n\x0c\x43learRequest\" \n\rClearResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x86\x02\n\x0cSearchWorker\x12=\n\x0cInsertVector\x12\x15.engine.InsertRequest\x1a\x16.engine.InsertResponse\x12>\n\rSearchVectors\x12\x15.engine.SearchRequest\x1a\x16.engine.SearchResponse\x12<\n\x0bHealthCheck\x12\x15.engine.HealthRequest\x1a\x16.engine.HealthResponse\x12\x39\n\nClearIndex\x12\x14.engine.ClearRequest\x1a\x15.engine.ClearResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_engine.app.proto.engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST']._serialized_start=48
  _globals['_INSERTREQUEST']._serialized_end=114
  _globals['_INSERTRESPONSE']._serialized_start=116
  _globals['_INSERTRESPONSE']._serialized_end=166
  _globals['_SEARCHREQUEST']._serialized_start=168
  _globals['_SEARCHREQUEST']._serialized_end=214
  _globals['_SEARCHRESULT']._serialized_start=216
  _globals['_SEARCHRESULT']._serialized_end=280
  _globals['_SEARCHRESPONSE']._serialized_start=282
  _globals['_SEARCHRESPONSE']._serialized_end=337
  _globals['_HEALTHREQUEST']._serialized_start=339
  _globals['_HEALTHREQUEST']._serialized_end=354
  _globals['_HEALTHRESPONSE']._serialized_start=356
  _globals['_HEALTHRESPONSE']._serialized_end=402
  _globals['_CLEARREQUEST']._serialized_start=404
  _globals['_CLEARREQUEST']._serialized_end=418
  _globals['_CLEARRESPONSE']._serialized_start=420
  _globals['_CLEARRESPONSE']._serialized_end=452
  _globals['_SEARCHWORKER']._serialized_start=455
  _globals['_SEARCHWORKER']._serialized_end=717
# @@protoc_insertion_point(module_scope)
